name: portal-web

services:
  front:
    container_name: front-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-frontend
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    ports: 
      - 8001:3000
    volumes:
      - ./app/frontend:/home/node/app
    command: >
      bash -c "npm install
                npm run start"
    networks:
      - net-portal

  back:
    container_name: back-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-backend
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    ports: 
      - 8002:3000
    volumes:
      - ./app/backend:/home/node/app
    command: >
      bash -c "yarn install
                npm run dev"
    networks:
      - net-portal

networks:
  net-portal: